### ISSUE TITLE
ML4MI _2024-03-19: Advancing Foundation Models for Cellular Morphology #98

### ISSUE THREAD

**Issue by Aman13567** [UW-Madison-DataScience/ML-X-Nexus#111]
Hi @jccaicedo,

I'm working on adding a large backlog of ML4MI recordings to Nexus and was wondering if you'd be willing to create a post for your talk from March.

It would follow a format similar to Anoop’s talk, Using EHR Data to Predict Deterioration in Hospitalized Children:
https://uw-madison-datascience.github.io/ML-X-Nexus/Applications/

Here’s what we’d need:

A short paragraph summarizing your talk.
Tags that capture the relevant ML/AI categories.
An image to accompany the post (you could generate one using a tool like ChatGPT/genAI, or use a screenshot from one of your slides).
We also have a detailed guide on how to contribute. Here’s a quick summary of the process:

Typically, you’d start by posting an issue to Nexus to announce your intended contribution and get feedback. (No need this time—I’ve already created the issue).
Once feedback is received, fork the Nexus repo. (Again, you can skip this step since I’m requesting the resource).
Copy one of the template files in the templates folder (e.g., the talk template). Alternatively, you can start by copying Anoop’s talk file for reference.
Edit the template to reflect your talk.
Move the completed file to the appropriate folder (e.g., Applications/Videos for this case).
Commit and push your changes to your fork.
Start a pull request to merge your fork into the main repo.
In the future, we’d also be thrilled if you could share other AI/ML resources from your lab that might benefit AI/ML practitioners across campus. This post could serve as a great starting point for ongoing contributions.

Looking forward to your input!

**Comment by qualiaMachine** [comment]
@Aman13567 This looks like a repeat issue of what I've already posted. You can post an issue if there's any specific resource you'd like to add to Nexus.
