### ISSUE TITLE
Design change suggestions

### ISSUE THREAD

**Issue by navin2uw** [UW-Madison-DataScience/ML-X-Nexus#19]
Per Chris' request, I am including my design suggestions to better align with [the brand guidelines](https://docs.google.com/presentation/d/1wYXfHgvwp_KCHEFDIoH_xQ-d_HBraJFrKTD1JxZcdbE/edit?usp=sharing).
- Please use this logo ([.svg](https://drive.google.com/file/d/1z4dKkZ3cAjTgbFu10KHe9FNa8XCHmPsF/view?usp=drive_link)) ([.png](https://drive.google.com/file/d/1fFxFEuicDiv67EScwgExvpGg9Go8GlEx/view?usp=drive_link)) instead.
- Also, try and use colors from the color palette. So perhaps:
- Left column has background #DADFE1 or #BBD7D8 with text color #282728. Highlighted and active menu links in #9B0000.
- In the content area, normal white #ffffff is good, otherwise #f7f7f7. Text color #282728.
- Text fonts should be [Montserrat](https://fonts.google.com/specimen/Montserrat) for headings and [Atkinson Hyperlegible](https://fonts.google.com/specimen/Atkinson+Hyperlegible) for body.

**Comment by qualiaMachine** [comment]
Thanks, @navin2uw! Would anyone from @UW-Madison-DataScience/nexus-developers be willing to tackle these changes? I'm trying to get Nexus ready for launch by the ML Marathon kickoff date (7/25). The earlier the better!

**Comment by sverchkov** [comment]
@navin2uw what about the dark mode color scheme?

**Comment by sverchkov** [comment]
For the logo, are we sure we want to lose the tagline? What we're using right now is a transparent version of the secondary with the tagline.

**Comment by sverchkov** [comment]
Indeed, the look of the primary logo on a red background looks a bit clunky with the light sidebar theming: 
![image](https://github.com/UW-Madison-DataScience/ML-X-Nexus/assets/2293026/0b81088f-5709-4e5e-85b1-df0f82d697a2)

I can think of 3 alternatives:
1. Make the sidebar background red. In that case we will need to think about a contrasting color choice for the sidebar elements and active links in the sidebar.
2. Use the secondary logo and make the sidebar background white.
3. Use a transparent version of the secondary logo (this is currently missing from our brand files)

**Comment by qualiaMachine** [comment]
Thanks for tinkering with this, @sverchkov. I agree that version looks clunky. I think option #3 might be best. The concern with the tagline was that it doesn't contrast well when viewed in the dark theme, and it's a little small to read in general. @navin2uw when you have a sec, could you upload the illustrator/indesign file you used for the logo to Google drive? I can export the transparent version from there.

We might might to explore adjusting the color for the dark theme just slightly so it contrasts better with the logo red.

**Comment by navin2uw** [comment]
Ohhh I must have overlooked making transparent versions for those. So, @qualiaMachine, I designed the logo in Canva; if you follow the instructions under the Badges section in my offboarding document, you can also access all the versions. You _might_ have to activate the free trial. Otherwise, I would just run the current version in our files through a transparency maker online, or in Illustrator, if that's easier.
