### ISSUE TITLE
[Feature Request] Check for broken links

### ISSUE THREAD

**Issue by qualiaMachine** [UW-Madison-DataScience/ML-X-Nexus#20]
We'll need to add some functionality to check for broken links periodically. It might make sense to use a github action to do this each time we commit to the repo, but I'm open to alternative approaches.

**Comment by qualiaMachine** [comment]
@welch16 Would you be willing to tackle this one when you have a moment?

**Comment by sverchkov** [comment]
Added a github action for this: https://github.com/UW-Madison-DataScience/ML-X-Nexus/commit/6efafae4454d5915b490a543d2c5af6f36b9ebee

Also, found a broken link!

**Comment by qualiaMachine** [comment]
Thanks, @sverchkov !
