### ISSUE TITLE
[Feature request] Post comments / Q&A

### ISSUE THREAD

**Issue by qualiaMachine** [UW-Madison-DataScience/ML-X-Nexus#23]
Some mechanism that allows users to post follow-up comments and/or questions on each post might be worthwhile to try. We should probably moderate comments just to be safe.

**Comment by sverchkov** [comment]
We could turn on Q&A on the GitHub repo. Enabling comments on the website side of things may be beyond what Quarto was made for.

**Comment by qualiaMachine** [comment]
GitHub Q&A seems like a good option. Sticking to questions and avoiding general comments is probably safer as well. 

Just enabled Discussions. I can add some language to the template resource file that points people to the discussion page.
