### ISSUE TITLE
[Resource] Kaggle Getting Started

### ISSUE THREAD

**Issue by qualiaMachine** [UW-Madison-DataScience/ML-X-Nexus#25]
I'm wondering if we might want to compile some resources on becoming acquainted with the Kaggle platform to help out the Machine Learning Marathon participants. @lexu27 Would you be interested in offering some of your insights on this? Maybe we can just link to a few useful Kaggle docs?

**Comment by lexu27** [comment]
I'm pretty sure that Kaggle's platform is already well-documented. It's almost the same thing as JupyterLab.

**Comment by qualiaMachine** [comment]
@lexu27 I just mean a useful summary of how to do basic things like:
* Create your account
* Register your team
* Configure git with Kaggle

Beyond technical aspects, we could also share some tips for tackling challenges or anything else that might be useful to share with someone that hasn't competed in one of these competitions before. Maybe that's overkill and folks can figure it out, but I'm just trying to make the hackathon as accessible as possible to folks that are new to the platform.
