### ISSUE TITLE
[Bug] Order by functionality broken

### ISSUE THREAD

**Issue by qualiaMachine** [UW-Madison-DataScience/ML-X-Nexus#32]
It looks like the "Order by" functionality seen on the Resources page (as well as the home page) is not working correctly.

**Comment by qualiaMachine** [comment]
@UW-Madison-DataScience/nexus-developers anyone available to do a little sleuthing on this? Sometime this week or next ideally.

FYI, there are several sort menus (all of which appear broken):
- https://uw-madison-datascience.github.io/ML-X-Nexus/
- https://uw-madison-datascience.github.io/ML-X-Nexus/Resources/
- https://uw-madison-datascience.github.io/ML-X-Nexus/Applications/

**Comment by sverchkov** [comment]
I can take a look.

For date order, there are no meaningful dates to sort by (sorts by last modified, but every time the site is rebuilt everything is "modified").

**Comment by qualiaMachine** [comment]
Thanks, @sverchkov !

**Comment by sverchkov** [comment]
Yeah... I can't figure out why title sorting through the UI does what it does on the main page.
I'll try to build a minimal reproducible example and submit an issue Quarto.

On the other pages sorting technically works correctly, it's just there's nothing other than the title to sort by.
For our specific case, since we have nothing but titles to sort by, perhaps we should get rid of the sorting UI altogether on these listings?

**Comment by qualiaMachine** [comment]
Glad I'm not the only one who was stumped. Thanks for building the test case for Quarto to investigate. I agree that it's probably not very useful to sort by title. I'll turn off the sort capacity for now, but I'm going to see if there's a good way to retain a more meaningful "last-modified" date.

**Comment by sverchkov** [comment]
It's probably not too bad of a solution to manually specify dates on all of those resources.

**Comment by qualiaMachine** [comment]
Yeah, I ended up using manually entered date fields. I've set the resources to display by "date asc" as the default view, and will keep the sort UI off unless we find a good reason to use it again. Closing the issue, thanks for the help investigating @sverchkov!

**Comment by sverchkov** [comment]
Ascending means oldest first, right? Don't we want to showcase the most recent additions?

**Comment by qualiaMachine** [comment]
Yeah, I'm using ascending for now as a hacky way to display our early/high-priority resource additions which have broad appeal. I think we can switch to descending soon once there are more meaningful resources to select from. Ideally we could pin a couple of the resources on the homepage and then sort by descending date.

**Comment by sverchkov** [comment]
From what I can tell the sort UI was sorting by filename instead of title. That's certainly a bug. https://github.com/quarto-dev/quarto-cli/issues/10398

**Comment by qualiaMachine** [comment]
Nice sleuthing!
