### ISSUE TITLE
Music classification blog post?

### ISSUE THREAD

**Issue by alanngnet** [UW-Madison-DataScience/ML-X-Nexus#67]
Idea for Nexus blog post maybe? I could write an intro to my project at https://github.com/alanngnet/CoverHunterMPS with the angle of: 1) example of application of deep learning for humanities research, 2) looking for collaborators, 3) the documentation in the project readme might be useful as a high level summary of the steps in general for someone new to ML to take any dataset and come out with a working classification solution.

**Comment by qualiaMachine** [comment]
Sounds like a perfect fit for a Nexus blog! Thanks @alanngnet, for getting the ball rolling. Let me know if you run into any snags adding the blog via a pull request — see [How to Contribute](https://uw-madison-datascience.github.io/ML-X-Nexus/Learn/Guides/How-to-contribute.html) for details. I've also just created a [template ](https://github.com/UW-Madison-DataScience/ML-X-Nexus/blob/main/Contributor-templates/template_blog.qmd) you can use as a starting point (mostly to help with formatting, the blogs are very open-ended). Happy to answer any questions.
